apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upgrader.yaml
  - upgrader-role.yaml

configMapGenerator:
  - name: upgrader-config
    behavior: create
    files:
      - config.yaml

secretGenerator:
  - name: upgrader-token
    behavior: create
    type: Opaque
    literals:
      - UPGRADER_TOKEN="${base64Secret}"