apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../features/k8spermissions/clusteradmin

namePrefix: PUT_YOUR_DELEGATE_NAME
namespace: harness-delegate-ng

configMapGenerator:
  - name: delegate-config
    behavior: merge
    literals:
      - LOG_STREAMING_SERVICE_URL="https://app.harness.io/gratis/log-service/"
      - DELEGATE_TAGS=""
      - ACCOUNT_ID=PUT_YOUR_ACCOUNT_ID
      - MANAGER_HOST_AND_PORT="https://app.harness.io/gratis"
      - DELEGATE_NAMESPACE="harness-delegate-ng"

secretGenerator:
  - name: account-token
    behavior: replace
    literals:
      - DELEGATE_TOKEN=PUT_YOUR_TOKEN

images:
  - name: harness/delegate
    newName: harness/delegate:22.11.77436
    newTag: v1
  - name: harness/upgrader
    newName: harness/upgrader:latest
    newTag: v1

replicas:
  - name: -delimiter-delegate
    count: 1

replacements:
  - source:
      kind: Secret
      version: v1
      name: account-token
      fieldPath: data.DELEGATE_TOKEN
    targets:
      - select:
          kind: Secret
          version: v1
          name: upgrader-token
        fieldPaths:
          - data.UPGRADER_TOKEN
  - source:
      kind: Deployment
      name: -delimiter-delegate
      group: apps
      version: v1
      options:
        delimiter: '-delimiter-'
        index: 0
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: -delimiter-delegate
          group: apps
          version: v1
        fieldPaths:
          - metadata.labels.[harness.io/name]
          - spec.selector.matchLabels.[harness.io/name]
          - spec.template.metadata.labels.[harness.io/name]
      - select:
          kind: ConfigMap
          name: delegate-config
          version: v1
        fieldPaths:
          - data.DELEGATE_NAME
      - select:
          kind: CronJob
          group: batch
          version: v1
          name: upgrader-job
        options:
          delimiter: '-'
          index: 0
        fieldPaths:
          - metadata.labels.[harness.io/name]
