apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-namespace-admin
  namespace: ${delegateNamespace}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-namespace-admin
  namespace: ${delegateNamespace}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${delegateNamespace}
roleRef:
  kind: Role
  name: harness-namespace-admin
  apiGroup: rbac.authorization.k8s.io