apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: harness-delegate-ng

secretGenerator:
  - name: client-certificate
    behavior: create
    type: Opaque
    literals:
      - client.crt="{CERT}"
      - client.key="{KEY}"


patchesJson6902:
  - target:
      kind: CronJob
      group: batch
      version: v1
      name: upgrader-job
    path: patch-upgrader.yaml
  - target:
      kind: Deployment
      group: app
      version: v1
      name: -delimiter-delegate
    path: patch-delegate.yaml


# TODO: there is currently no support for merging two files into one. It requires a customized generator plugin
configMapGenerator:
  - name: upgrader-config
    namespace: harness-delegate-ng
    behavior: merge
    literals:
      - clientCertificateFilePath=/etc/mtls/client.crt
      - clientCertificateKeyFilePath=/etc/mtls/client.key
  - name: delegate-config
    namespace: harness-delegate-ng
    behavior: merge
    envs:
      - delegate-mtls-environment.env