- op: add
  path: /spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-
  value:
    name: client-certificate
    mountPath: /etc/mtls
    readOnly: true
- op: add
  path: /spec/jobTemplate/spec/template/spec/volumes/-
  value:
    name: client-certificate
    secret:
      secretName: client-certificate
